USE VRAJ_PATEL;

SELECT SUM(AMOUNT) FROM DEPOSIT;
SELECT SUM(AMOUNT) FROM BORROW WHERE BNAME = 'KAROLBAGH';
SELECT MAX(AMOUNT) FROM BORROW WHERE BNAME = 'VRCE';
SELECT COUNT(CNAME) FROM CUSTOMER;
SELECT COUNT(DISTINCT CITY) FROM CUSTOMER;
CREATE TABLE SUPPLIER AS SELECT * FROM EMPLOYEE;
CREATE TABLE SUP1 AS SELECT EMP_NO,EMP_NAME FROM EMPLOYEE;
CREATE TABLE SUP2 AS SELECT * FROM EMPLOYEE WHERE EMP_NO = NULL;
INSERT INTO SUP2(EMP_NO) SELECT(EMP_NO) FROM EMPLOYEE WHERE EMP_NAME LIKE '_n___';
TRUNCATE TABLE SUP1;
DELETE FROM SUPPLIER WHERE EMP_NO = '103'; 
RENAME TABLE SUP2 TO SUP3;
DROP TABLE SUP1;
UPDATE EMPLOYEE SET DEPT_NO = '10' WHERE EMP_NAME LIKE '_m%';
UPDATE EMPLOYEE SET EMP_NAME = 'DARSHAN' WHERE EMP_NO = '103';