USE VRAJ_PATEL;

SELECT current_date() AS "DATE" FROM DUAL;
SELECT EMP_NO, EMP_NAME, EMP_SAL, EMP_SAL+(EMP_SAL*15/100)"NEW SALARY" FROM EMPLOYEE;
SELECT EMP_NO, EMP_NAME, EMP_SAL, EMP_SAL+(EMP_SAL*15/100)"NEW SALARY", (EMP_SAL+(EMP_SAL*15/100))-EMP_SAL"INCREASE" FROM EMPLOYEE;
SELECT CapitalizeWords(EMP_NAME)"NAME" , LENGTH(EMP_NAME)"LENGTH OF NAME" FROM EMPLOYEE WHERE EMP_NAME LIKE 'J%' OR EMP_NAME LIKE 'A%' OR EMP_NAME LIKE 'M%' ORDER BY EMP_NAME;
SELECT EMP_NAME, ' earns ', EMP_SAL, ' monthly ' FROM EMPLOYEE;
SELECT EMP_NAME, HIRE_DATE, TIMESTAMPDIFF(MONTH, HIRE_DATE, CURRENT_DATE()) AS MONTHS_EMPLOYED ,DAYNAME(HIRE_DATE) AS DAY_OF_WEEK FROM EMPLOYEE ORDER BY FIELD(DAYOFWEEK(HIRE_DATE), 2, 3, 4, 5, 6, 7, 1);
SELECT DATE_FORMAT(HIRE_DATE, '%D OF %M %Y %l:%i:%s %p') AS FORMATTED_HIRE_DATE FROM EMPLOYEE;
SELECT (EMP_SAL + IFNULL(EMP_COMM,0) )*12 "COMPENSATION" FROM EMPLOYEE;