USE VRAJ_PATEL;

SELECT * FROM EMPLOYEE;
SELECT * FROM JOB;
SELECT * FROM DEPOSIT;

SELECT ACTNO, AMOUNT FROM DEPOSIT WHERE ADATE BETWEEN '1996-01-01' AND '1996-07-25';
SELECT * FROM JOB WHERE MIN_SAL > '15000';
SELECT EMP_NAME AS "NAME", EMP_SAL FROM EMPLOYEE WHERE DEPT_NO = '20';
SELECT EMP_NO, EMP_NAME, DEPT_NO FROM EMPLOYEE WHERE DEPT_NO IN (10,20);
SELECT * FROM EMPLOYEE WHERE EMP_NAME LIKE 'A_a%';
SELECT EMP_NAME, EMP_NO, EMP_SAL FROM EMPLOYEE WHERE EMP_NAME LIKE 'Ani__%';

SELECT * FROM EMPLOYEE WHERE EMP_COMM IS NOT NULL AND EMP_NAME LIKE '_n___';
SELECT * FROM EMPLOYEE WHERE EMP_COMM IS NULL AND EMP_NAME LIKE '__a%';